go/games/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from games.views import CreatePageView

urlpatterns = [
    url(r'^new$', login_required(CreatePageView.as_view(), login_url=reverse_lazy('core:welcome')), name='new'),
    url(r'^games/(?P<game_id>\d+)?$', 'games.views.show_page', name='show_page'),
    url(r'^games/(?P<game_id>\d+)/move$', 'games.sgf.record'),
    url(r'^games/(?P<game_id>\d+)/load$', 'games.sgf.load'),
    url(r'^games/(?P<game_id>\d+)/time$', 'games.sgf.time'),
    url(r'^games/(?P<game_id>\d+)/status$', 'games.game.status'),
    url(r'^games/(?P<game_id>\d+)/surrender$', 'games.game.surrender'),
    url(r'^games/(?P<game_id>\d+)/comments$', 'games.game.comments', name='comments'),
    url(r'^callings/(?P<call_id>\d+)?$', 'games.views.show_callings', name='show_callings'),
    url(r'^callings/(?P<call_id>\d+)/accept$', 'games.views.accept', name='accept'),
    url(r'^callings/check', 'games.views.calls_check'),
    url(r'^callings/recd', 'games.views.received_accept'),
]

go/go/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from go import settings

urlpatterns = [
    # url(r'^', include('django_socketio.urls')),
    url(r'^', include('core.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ladders/', include('ladders.urls', namespace='ladders')),
    url(r'^words/', include('words.urls', namespace='words')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^', include('games.urls', namespace='games')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

go/users/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^(?P<user_id>\d+)/$', 'users.views.profile_page', name='profile_page'),
    url(r'^(?P<user_id>\d+)/games/now$', 'users.views.grid_now', name='now'),
    url(r'^(?P<user_id>\d+)/games/all$', 'users.views.grid_all', name='all'),
    url(r'^settings/$', 'users.views.settings_page', name='settings'),
]

go/games/models.py
import datetime
from django.db import models
from users.models import Profile
from words.models import Comment

GAME_RESULT = (
    ('W', 'White wins'),
    ('B', 'Black wins'),
    ('N', 'Dead heat')
)


# Create your models here.
class GameInfo(models.Model):
    title = models.CharField(max_length=120, default='Friendly match')
    handicap = models.PositiveSmallIntegerField(default=0)
    komi = models.FloatField(default=6.5)
    board_size = models.PositiveSmallIntegerField(default=19)

    main_basic_time = models.TimeField()
    white_basic_time = models.TimeField(default=datetime.datetime.now())
    black_basic_time = models.TimeField(default=datetime.datetime.now())
    main_byo_yomi = models.TimeField()
    main_byo_yomi_periods = models.PositiveSmallIntegerField(default=3)
    white_byo_yomi_periods = models.PositiveSmallIntegerField(default=0)
    black_byo_yomi_periods = models.PositiveSmallIntegerField(default=0)

    kifu = models.TextField(default="(;FF[4])")
    comments = models.ManyToManyField(Comment)
    result = models.CharField(max_length=1, blank=True, choices=GAME_RESULT)

    def __unicode__(self):
        return "%s, %s board size, %s handicap, %s komi, %s basic time, %s byo-yomi" % (
            self.title, self.board_size, self.handicap, self.komi, self.main_basic_time, self.main_byo_yomi
        )


class Game(models.Model):
    game_info = models.ForeignKey(GameInfo)
    white = models.ForeignKey(Profile, related_name='white')
    black = models.ForeignKey(Profile, related_name='black')
    game_date = models.DateTimeField(auto_now=True)
    winner = models.ForeignKey(Profile, related_name='winner', null=True, blank=True)

    def __unicode__(self):
        return "%s between %s(b) and %s(w) | Result: %s" % (
            self.game_info.title, self.black.user.username, self.white.user.username, self.game_info.result
        )


class Calling(models.Model):
    game_info = models.ForeignKey(GameInfo)
    caller = models.ForeignKey(Profile, related_name='caller')
    accepter = models.ForeignKey(Profile, related_name='accepter', null=True, blank=True)
    accepted = models.BooleanField(default=False)

    def __unicode__(self):
        return "from %s" % self.caller.user.username

go/words/models.py
from django.db import models

# Create your models here.
from users.models import Profile


class Room(models.Model):
    title = models.CharField(max_length=16)
    users = models.ManyToManyField(Profile)

    def __unicode__(self):
        return self.title


class Message(models.Model):
    sender = models.ForeignKey(Profile)
    room = models.ForeignKey(Room)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s | %s | %s" % (self.room, self.sender, self.text)


class Comment(models.Model):
    sender = models.ForeignKey(Profile)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s at %s: %s" % (self.sender, self.pub_date, self.text)

go/games/forms.py
from django import forms
from games.models import Calling, GameInfo

BOARD_SIZE = (
    ('19', '19x19'),
    ('13', '13x13'),
    ('9', '9x9')
)

BASIC_TIME = (
    ('00:00:00', 'None'),
    ('00:00:30', '30 seconds'),
    ('00:00:45', '45 seconds'),
    ('00:01:00', '1 minute'),
    ('00:01:15', '1 minute 15 seconds'),
    ('00:01:30', '1 minute 30 seconds'),
    ('00:01:45', '1 minute 45 seconds'),
    ('00:02:00', '2 minutes'),
    ('00:02:30', '2 minutes 30 seconds'),
    ('00:03:00', '3 minutes'),
    ('00:03:30', '3 minutes 30 seconds'),
    ('00:04:00', '4 minutes'),
    ('00:04:30', '4 minutes 30 seconds'),
    ('00:05:30', '5 minutes'),
    ('00:06:00', '6 minutes'),
    ('00:07:00', '7 minutes'),
    ('00:08:00', '8 minutes'),
    ('00:09:00', '9 minutes'),
    ('00:10:00', '10 minutes'),
    ('00:15:00', '15 minutes'),
    ('00:20:00', '20 minutes'),
    ('00:25:00', '25 minutes'),
    ('00:30:00', '30 minutes'),
    ('00:35:00', '35 minutes'),
    ('00:40:00', '40 minutes'),
    ('00:45:00', '45 minutes'),
    ('00:50:00', '50 minutes'),
    ('00:55:00', '55 minutes'),
    ('01:00:00', '1 hour'),
    ('01:15:00', '1 hour 15 minutes'),
    ('01:30:00', '1 hour 30 minutes'),
    ('01:45:00', '1 hour 45 minutes'),
    ('02:00:00', '2 hours'),
    ('02:15:00', '2 hours 15 minutes'),
    ('02:30:00', '2 hours 30 minutes'),
    ('02:45:00', '2 hours 45 minutes'),
    ('03:00:00', '3 hours')
)

BYO_YOMI = (
    ('00:00:10', '10 seconds'),
    ('00:00:12', '12 seconds'),
    ('00:00:15', '15 seconds'),
    ('00:00:20', '20 seconds'),
    ('00:00:25', '25 seconds'),
    ('00:00:30', '30 seconds'),
    ('00:00:35', '35 seconds'),
    ('00:00:40', '40 seconds'),
    ('00:00:45', '45 seconds'),
    ('00:00:50', '50 seconds'),
    ('00:00:55', '55 seconds'),
    ('00:01:00', '1 minute'),
    ('00:01:10', '1 minutes 10 seconds'),
    ('00:01:20', '1 minutes 20 seconds'),
    ('00:01:30', '1 minutes 30 seconds'),
    ('00:01:40', '1 minutes 40 seconds'),
    ('00:01:50', '1 minutes 50 seconds'),
    ('00:02:00', '2 minutes'),
    ('00:02:20', '2 minutes 20 seconds'),
    ('00:02:40', '2 minutes 40 seconds'),
    ('00:03:00', '3 minutes'),
    ('00:03:30', '3 minutes 30 seconds'),
    ('00:04:00', '4 minutes'),
    ('00:04:30', '4 minutes 30 seconds'),
    ('00:05:30', '5 minutes'),
    ('00:06:00', '6 minutes'),
    ('00:07:00', '7 minutes'),
    ('00:08:00', '8 minutes'),
    ('00:09:00', '9 minutes'),
    ('00:10:00', '10 minutes'),
)


class NewGameForm(forms.ModelForm):
    board_size = forms.ChoiceField(choices=BOARD_SIZE)
    main_basic_time = forms.ChoiceField(choices=BASIC_TIME)
    main_byo_yomi = forms.ChoiceField(choices=BYO_YOMI)

    class Meta:
        model = GameInfo
        exclude = ['kifu', 'result', 'white_byo_yomi_periods', 'white_basic_time',
                   'black_basic_time', 'black_byo_yomi_periods', 'comments']

go/games/views.py
import datetime
import json
from django.utils.safestring import SafeString
from django.views.generic import View
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy, reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render

# Create your views here
from games.forms import NewGameForm
from games.models import Calling, GameInfo, Game
from games.sgf import _initiate
from users.models import Profile


@login_required(login_url=reverse_lazy("home:welcome_page"))
def show_page(request, game_id=None):
    if game_id is not None:
        game_info = GameInfo.objects.get(id=game_id)
        game = Game.objects.get(game_info=game_info)
        return render(request, "games/game.html", {"headline": game_info.title,
                                                   "game_info": game_info,
                                                   "game": game,
                                                   "user": request.user,
                                                   "comments": GameInfo.objects.get(id=game_id).comments.all().order_by('-pub_date').iterator(),
                                                   "comments_l": GameInfo.objects.get(id=game_id).comments.count()})

    else:
        i = 0
        response = {}

        now_played = Game.objects.exclude(winner__isnull=False)
        played = Game.objects.exclude(winner__isnull=True)

        for game in now_played.iterator():
            response[i] = {"game_size": game.game_info.board_size,
                           "game_id": game.game_info.id,
                           "now": True,
                           "black": game.black.user.username,
                           "black_rating": game.black.rating,
                           "white": game.white.user.username,
                           "white_rating": game.white.rating}
            i += 1

        for game in played.iterator():
            response[i] = {"game_size": game.game_info.board_size,
                           "game_id": game.game_info.id,
                           "now": False,
                           "black": game.black.user.username,
                           "black_rating": game.black.rating,
                           "white": game.white.user.username,
                           "white_rating": game.white.rating}
            i += 1

        return render(request, "games/grid.html", {"headline": "All games",
                                                   "json": SafeString(json.dumps(response))})


@login_required(login_url=reverse_lazy("home:welcome_page"))
def show_callings(request, call_id=None):
    if call_id is not None:
        return render(request, "games/calls.html", {'callings': True})
    return render(request, "games/calls.html", {'headline': "Callings",
                                                'callings': Calling.objects.exclude(accepter__isnull=False),
                                                'hours': datetime.time(hour=2),
                                                'minutes': datetime.time(minute=1),
                                                'seconds': datetime.time(second=1)})


class CreatePageView(View):
    form_class = NewGameForm
    template_name = 'games/new.html'
    headline = 'New game'

    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'headline': self.headline, 'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            game_info = GameInfo(title=form.cleaned_data['title'],
                                 handicap=form.cleaned_data['handicap'],
                                 komi=form.cleaned_data['komi'],
                                 board_size=form.cleaned_data['board_size'],
                                 main_basic_time=form.cleaned_data['main_basic_time'],
                                 main_byo_yomi=form.cleaned_data['main_byo_yomi'],
                                 main_byo_yomi_periods=form.cleaned_data['main_byo_yomi_periods'])
            game_info.save()

            call = Calling(game_info=game_info,
                           caller=Profile.objects.get(user=request.user))
            call.save()

            return HttpResponseRedirect(reverse_lazy("games:show_callings"))

        else:
            render(request, self.template_name, {'headline': self.headline, 'form': form})


@login_required(login_url=reverse_lazy("home:welcome_page"))
def accept(request, call_id=None):
    if call_id and request.method == 'POST':

        call = Calling.objects.get(id=call_id)
        user = Profile.objects.get(user=request.user)

        if call.caller.rating >= user.rating:
            new_game = Game(game_info=call.game_info,
                            white=call.caller,
                            black=user)
        else:
            new_game = Game(game_info=call.game_info,
                            white=user,
                            black=call.caller)

        new_game.save()
        _initiate(call.game_info.id)

        call.accepter = user
        call.accepted = True
        call.save()
        return HttpResponseRedirect(reverse_lazy("games:show_page", args=[call.game_info.id]))
    return HttpResponseRedirect(reverse_lazy("games:show_callings"))


@login_required
def calls_check(request):
    user = Profile.objects.get(user=request.user)
    calls = Calling.objects.filter(caller=user).exclude(accepted=True).exclude(accepter__isnull=True)

    i = 0
    response = {}
    for item in calls:
        response[i] = reverse('games:show_page', args=[Calling.objects.get(id=item.id).game_info.id])
        i += 1

    return HttpResponse(json.dumps(response))


@login_required
def received_accept(request):
    if request.method == 'POST':
        id = request.POST['game_id']
        call = Calling.objects.get(game_info=GameInfo.objects.get(id=id))
        print 1
        call.accepted = True
        call.save()
        return HttpResponse("Ok")

go/games/templates/games/calls.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <form id="accept-form" action="" class="full-width-form mfp-hide upload-file-popup" method="POST">
            {% csrf_token %}
            <h2>default</h2>

            <hr class="divider">

                <p>Caller: <span>{{ callings.0.caller }}</span></p>
                <p>Rank: <span>{{ callings.0.caller.rating }}</span></p>
                <p>Board size: <span>{{ callings.0.game_info.board_size }}</span></p>
                <p>Handicap: <span>{{ callings.0.game_info.handicap }}</span></p>
                <p>Komi: <span>{{ callings.0.game_info.komi }}</span></p>
                <p>Basic time: <span>{{ callings.0.game_info.main_basic_time|date:"H:i:s" }}</span></p>
                <p>Byo-yomi: <span>{{ callings.0.game_info.byo_yomi|date:"i:s" }}</span></p>
                <p>Periods: <span>{{ callings.0.game_info.byo_yomi_periods }}</span></p>

            <hr class="divider">

            <input id="accept-button" type="submit" value="accept">
        </form>


        <div id="calls-table" class="eleven columns">

            {% if callings %}
                <table id="table" class="u-full-width">
                    <thead>
                        <tr>
                            <th>caller</th>
                            <th>rank</th>
                            <th>board size</th>
                            <th>handicap</th>
                            <th>komi</th>
                            <th>basic time</th>
                            <th>byo-yomi</th>
                            <th>periods</th>
                            <th>match name</th>
                            <th style="padding-left: 10%">action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for call in callings %}
                            <tr>
                                <td><a href="{% url "profile:profile_page" call.caller.user.id %}">{{ call.caller.user.username }}</a></td>
                                <td>{{ call.caller.rating }}</td>
                                <td>{{ call.game_info.board_size }}x{{ call.game_info.board_size }}</td>
                                <td>{{ call.game_info.handicap }}</td>
                                <td>{{ call.game_info.komi }}</td>
                                <td>{{ call.game_info.main_basic_time|date:"H:i:s" }}</td>
                                <td>{{ call.game_info.main_byo_yomi|date:"i:s"}}</td>
                                <td>{{ call.game_info.main_byo_yomi_periods }}</td>
                                <td>{{ call.game_info.title }}</td>
                                <td>
                                    <a id="{{ call.id }}" onclick="get_call({{ call.id }}, '{{ call.caller.user.username }}')" class="popup-with-form button u-pull-right" href="#accept-form">Accept</a>
                                  </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                No callings yet..
            {% endif %}
        </div>

        <div class="md-overlay"></div><!-- the overlay element -->

        <!-- Don't judge me -->
        <script>
            path = "{% url "games:accept" 1 %}".split("/");
            current_user = "{{ user }}";
        </script>

        <script src="{% static "js/callings-page.js" %}"></script>

    {% endblock content %}

go/games/templates/games/game.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <script>
            var game_id = {{ game_info.id }},
                    comments = {{ comments_l }}
                    title = '{{ game_info.title }}',
                    user = '{{ user.username }}',
                    black = '{{ game.black.user.username }}',
                    white = '{{ game.white.user.username }}',
                    hours_black = {{ game_info.black_basic_time|date:"G" }},
                    minutes_black = {{ game_info.black_basic_time|date:"i" }},
                    seconds_black = {{ game_info.black_basic_time|date:"s" }},
                    periods_black = {{ game_info.black_byo_yomi_periods }},
                    hours_white = {{ game_info.white_basic_time|date:"G" }},
                    minutes_white = {{ game_info.white_basic_time|date:"i" }},
                    seconds_white = {{ game_info.white_basic_time|date:"s" }},
                    periods_white = {{ game_info.white_byo_yomi_periods }},
                    byo_yomi_m = {{ game_info.main_byo_yomi|date:"i" }},
                    byo_yomi_s = {{ game_info.main_byo_yomi|date:"s" }};
        </script>

        <div class="eight columns">
            <img id="w-stone" src="{% static "images/w-stone.png" %}" style="display: none">
            <img id="bg" src="{% static "images/background1.png" %}" style="display: none;">
            <canvas id='desk' height="690" width="690" style="margin-top: -35px;"></canvas>
        </div>

        <div class="three columns" style="margin-top: -15px">
            <div id="black" class="stroke-block player" style="border-radius: 0; border: none">
                <div>
                    <a href="{% url "profile:profile_page" game.black.user.id %}" style="color: white">{{ game.black.user.username }}</a>
                    <h6 style="font-size: 0.9em">({{ game.black.rating }})</h6>
                    <h6 style="float: right; margin-right: 5px;">BLACK </h6>
                </div>

                <hr style="margin: 4px 0 5px 0; border-color: #343434">

                <div class="row">
                    <div>
                        <h6 id="basic_time_black">00:10</h6>
                        <h6 id="black_b" style="color: #777"><span id="byo_yomi_black">00:10</span> x <span id="periods_black">4</span></h6>
                    </div>
                </div>

                <hr style="margin: 4px 0 5px 0; border-color: #222">

                <div class="row">
                    <h6 style="font-weight: 500; margin-bottom:0 ">captured: 9</h6>
{#                    <h6 style="float: right; font-weight: 500; margin-bottom:0 ">captured: 9</h6>#}
                </div>
            </div>

            <hr style="visibility: hidden; margin: 7px auto">

            <div id="white" class="stroke-block player" style="border-radius: 0;">
                <div>
                    <a href="{% url "profile:profile_page" game.white.user.id %}" style="font-weight: 800; color: black">{{ game.white.user.username }}</a>
                    <h6 style="display: inline; font-weight: 800; color: black; font-size: 0.9em">({{ game.white.rating }})</h6>
                    <h6 style="margin-bottom: 0; float: right; margin-right: 5px; font-weight: 800; color: black;">WHITE</h6>
                </div>

                <hr style="margin: 4px 0 5px 0; border-color: #fafafa">

                <div class="row">
                    <div style="color: black">
                        <h6 id="basic_time_white">00:10</h6>
                        <h6 id="white_b" style="color: #999"><span id="byo_yomi_white">00:10</span> x <span id="periods_white">4</span></h6>
                    </div>
                </div>

                <hr style="margin: 4px 0 5px 0; border-color: #eee">

                <div class="row" style="color: black">
                    <h6 style="display: inline; font-weight: 500; margin-bottom:0 ">captured: 9</h6>
                    <h6 style="float: right; font-weight: 500; margin-bottom:0 ">komi: 6.5</h6>
                </div>
            </div>

            <div id="game-actions" class="row" style="margin-top: 20px; ">
                <button class="six columns button" type="button" disabled="disabled">Undo</button>
                <button id="surrender" class="six columns button" type="button">Give up</button>
            </div>

        </div>


        <div class="row">
            <div class="offset-by-one eleven columns">
{#                <h5 style="padding-top: 20px; margin-bottom: 10px">Comments:</h5>#}

                <div class="row" style="margin-top: 25px">
                    <div class="nine columns">
                        <input id="id_text" type="text" class="ten columns">
                        <input id="comment-form" class="u-pull-right" type="button" value="Send">
                        <hr style="margin-top: 60px; margin-bottom: 20px">
                        <div id="comments" class="with-scrollbar" style="max-height: 400px; overflow: auto">
                            {% if comments %}
                                {% for item in comments %}
                                    <p>
                                        {% if item.sender.user == user %}
                                            <a href="{% url "profile:profile_page" item.sender.user.id %}" style="font-weight: 800; text-decoration: none">{{ item.sender }}&nbsp;{{ item.pub_date|date:"(H:s, d.m.y)" }}</a> <br>
                                        {% else %}
                                            <a href="{% url "profile:profile_page" item.sender.user.id %}" style="text-decoration: none">{{ item.sender }}&nbsp;{{ item.pub_date|date:"(H:s, d.m.y)" }}</a> <br>
                                        {% endif %}
                                        {{ item.text }}
                                    </p>
                                {% endfor %}
                            {% else %}
                                Comments...
                            {% endif %}
                        </div>
                    </div>

                </div>

            </div>
        </div>

        <script src="{% static "js/goban/classes.js" %}"></script>
        <script src="{% static "js/goban/helpers.js" %}"></script>
        <script src="{% static "js/goban/draw.js" %}"></script>
        <script src="{% static "js/goban/main.js" %}"></script>

    {% endblock content %}

go/games/templates/games/grid.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <script>
            var comments = "";
            var json = '{{ json }}';
        </script>

        <div class="eleven columns">

            <img id="bg" src="{% static "images/background1.png" %}" style="display: none;">

            <div class="row games-grid" style="margin-top: 0.5%">
                <div class="four columns">
                    <div id="th_1"></div>
                    <div id="th_4" style="margin-top: 15px"></div>
                </div>
                <div class="four columns">
                    <div id="th_2"></div>
                    <div id="th_5" style="margin-top: 15px"></div>
                </div>
                <div class="four columns">
                    <div id="th_3"></div>
                    <div id="th_6" style="margin-top: 15px"></div>
                </div>
            </div>

            <div class="bottom">
                <a href="{% url "games:show_page" %}"><h6>next &nbsp;</h6><i class="fa fa-long-arrow-right"></i></a>
            </div>

        </div>

        <script src="{% static "js/goban/classes.js" %}"></script>
        <script src="{% static "js/goban/helpers.js" %}"></script>
        <script src="{% static "js/goban/draw.js" %}"></script>
        <script src="{% static "js/grid.js" %}"></script>

        <script>
            show(280, 280, 6, json, "th_", 13.5);
        </script>


    {% endblock content %}

go/games/templates/games/new.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <div class="five columns with-min-height" style="margin-top: -0.2%">
        <form class="full-width-form" action="{% url "games:new" %}" method="post">
            {% csrf_token %}
            {{ form }}
            <input class="button-primary u-full-width" type="submit" value="Submit">
        </form>

        </div>

        <div class="five columns u-full-width" style="margin-top: 1.75%">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at placerat mauris. Quisque mi erat, sagittis tincidunt est a, porta molestie purus. Morbi neque nisi, porta quis ipsum sit amet, pulvinar viverra purus. Sed et lorem dolor.
            </p>
        </div>


    {% endblock content %}