go/core/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from core import views

urlpatterns = [
    url(r'^$', 'core.views.home_page', name='home_page'),
    url(r'^about/$', TemplateView.as_view(template_name="core/about.html"), name="about_page"),
    url(r'^welcome/$', 'core.views.welcome_page', name='welcome_page'),
    url(r'^signout/$', 'core.views.sign_out', name='sign_out'),
    url(r'^signup/$', 'core.views.sign_up', name='sign_up'),
]

go/games/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from games.views import CreatePageView

urlpatterns = [
    url(r'^new$', login_required(CreatePageView.as_view(), login_url=reverse_lazy('core:welcome')), name='new'),
    url(r'^games/(?P<game_id>\d+)?$', 'games.views.show_page', name='show_page'),
    url(r'^games/(?P<game_id>\d+)/move$', 'games.sgf.record'),
    url(r'^games/(?P<game_id>\d+)/load$', 'games.sgf.load'),
    url(r'^games/(?P<game_id>\d+)/time$', 'games.sgf.time'),
    url(r'^games/(?P<game_id>\d+)/status$', 'games.game.status'),
    url(r'^games/(?P<game_id>\d+)/surrender$', 'games.game.surrender'),
    url(r'^games/(?P<game_id>\d+)/comments$', 'games.game.comments', name='comments'),
    url(r'^callings/(?P<call_id>\d+)?$', 'games.views.show_callings', name='show_callings'),
    url(r'^callings/(?P<call_id>\d+)/accept$', 'games.views.accept', name='accept'),
    url(r'^callings/check', 'games.views.calls_check'),
    url(r'^callings/recd', 'games.views.received_accept'),
]

go/go/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from go import settings

urlpatterns = [
    # url(r'^', include('django_socketio.urls')),
    url(r'^', include('core.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ladders/', include('ladders.urls', namespace='ladders')),
    url(r'^words/', include('words.urls', namespace='words')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^', include('games.urls', namespace='games')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

go/core/models.py
from django.core.files import File
from django.db import models


# Create your models here
from users.models import Profile


class Collection(models.Model):
    file = models.FileField(upload_to='games')
    comment = models.TextField(blank=True)
    upload_time = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(Profile)

    def __unicode__(self):
        return self.file.name

go/core/forms.py
from django import forms

GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
)


class SignInForm(forms.Form):
    username = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Username/Email'}))
    password = forms.CharField(label=False, widget=forms.TextInput(attrs={'placeholder': 'Password',
                                                                          'type': 'password'}))


class SignUpForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    email = forms.EmailField()
    first_name = forms.CharField(required=False)
    gender = forms.ChoiceField(required=False, choices=GENDER)

go/core/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.utils.safestring import SafeString

from core.forms import SignInForm, SignUpForm
# from django_sse.redisqueue import RedisQueueView



# Create your views here.
from games.models import Calling, Game
from users.models import Profile


@login_required(login_url=reverse_lazy("home:welcome_page"))
def home_page(request):
    i = 0
    response = {}

    now_played = Game.objects.exclude(winner__isnull=False)
    played = Game.objects.exclude(winner__isnull=True)

    for game in now_played.iterator():
        response[i] = {"game_size": game.game_info.board_size,
                       "game_id": game.game_info.id,
                       "now": True,
                       "black": game.black.user.username,
                       "black_rating": game.black.rating,
                       "white": game.white.user.username,
                       "white_rating": game.white.rating}
        i += 1

    for game in played.iterator():
        response[i] = {"game_size": game.game_info.board_size,
                       "game_id": game.game_info.id,
                       "now": False,
                       "black": game.black.user.username,
                       "black_rating": game.black.rating,
                       "white": game.white.user.username,
                       "white_rating": game.white.rating}
        i += 1

    return render(request, "core/home.html", {"games": True,
                                               "callings": Calling.objects.exclude(accepter__isnull=False)[:10],
                                               "json": SafeString(json.dumps(response))})


def welcome_page(request):
    if request.method == 'POST':
        form = SignInForm(request.POST)
        if form.is_valid():
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password']
            )
            if user is not None:
                login(request, user)
                if "next" in request.GET:
                    redirect = HttpResponseRedirect(request.GET["next"])
                else:
                    redirect = HttpResponseRedirect(reverse_lazy("home:home_page"))
                redirect.set_cookie("who", request.user.username, max_age=24 * 60 * 60)
                return redirect
            else:
                return render(request, 'core/welcome.html', {"headline": "Welcome",
                                                             "form": form,
                                                             'wrong': 'Whoops, can\'t find you ><'})
        else:
            return render(request, 'core/welcome.html', {"headline": "Welcome",
                                                         "form": form})

    form = SignInForm()
    if "who" in request.COOKIES:
        form.fields["username"].initial = request.COOKIES["who"]
    return render(request, "core/welcome.html", {"headline": "Welcome",
                                                 "form": form})


def sign_out(requset):
    if requset.user.is_authenticated():
        logout(requset)
        return HttpResponseRedirect(reverse("home:welcome_page"))
    else:
        return render(requset, 'blank.html', {'headline': 'Maaan, you don\'t even signed in -_-"',
                                              'message': 'Lorem bla ipsum bla dolor bla sit bla amet bla bla.'})


def sign_up(request):
    if request.user.is_anonymous():
        if request.method == 'POST':
            form = SignUpForm(request.POST)
            if form.is_valid():
                user = authenticate(
                    username=form.cleaned_data['username'],
                    password=form.cleaned_data['password']
                )
                if user is None:
                    user = User.objects.create_user(form.cleaned_data['username'],
                                                    form.cleaned_data['email'],
                                                    form.cleaned_data['password'])
                    user.first_name = form.cleaned_data['first_name']
                    profile = Profile(user=user)
                    if form.cleaned_data['gender']:
                        profile.gender = form.cleaned_data['gender']
                    user.save()
                    profile.save()
                    new_one = authenticate(username=form.cleaned_data['username'],
                                           password=form.cleaned_data['password'])
                    login(request, new_one)
                    return HttpResponseRedirect(reverse_lazy("home:home_page"))
                else:
                    return render(request, "core/signup.html", {"headline": "Sign Up",
                                                                "form": form})
            else:
                return render(request, "core/signup.html", {"headline": "Sign Up",
                                                            "form": form})
        form = SignUpForm()
        return render(request, "core/signup.html", {"headline": "Sign Up",
                                                    "form": form})
    else:
        return render(request, 'blank.html', {'headline': 'Wow, do you wanna sign up twice?!',
                                              'message': 'I think, that i am not so ... hmm.. demanding programmer '
                                                         'to let you do that if you already signed in. Think by yourself, dude.'})

go/core/templates/core/about.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <div class="eleven columns">
            <p>Nulla fringilla ac tellus id rutrum. Curabitur egestas euismod nunc ac ullamcorper. Nulla laoreet et est eget gravida. Nulla nunc est, pellentesque ac arcu eget, venenatis commodo orci. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In hac habitasse platea dictumst. Nunc fringilla dignissim hendrerit.</p>
            <p>Sed dignissim dignissim lorem a accumsan. Pellentesque mi justo, elementum vitae tristique at, fermentum vel ligula. Nunc dignissim odio id est porta laoreet tincidunt ac nunc. Nunc semper tellus dui, sed viverra velit rutrum id. Nulla quis metus id eros hendrerit vehicula. Mauris rhoncus nulla non odio suscipit, non rutrum mauris cursus. Maecenas feugiat auctor odio. Aliquam sed est nisi. Duis finibus cursus arcu a dapibus. Proin non erat ultricies nisl lobortis interdum.</p>
            <p>Quisque in nunc porta, tempor est ac, scelerisque metus. Aliquam rhoncus erat et sagittis mollis. Sed ullamcorper mauris sed sollicitudin ornare. Praesent vitae sapien sem. Cras diam nibh, luctus nec sapien tincidunt, scelerisque placerat nibh. Nunc ut diam a sapien congue euismod id ac massa. Donec hendrerit, nulla ut euismod pellentesque, nisl felis ultrices ipsum, nec mattis ligula mauris ac ex.</p>
            <p>Cras imperdiet dapibus facilisis. Mauris et cursus augue. Nunc facilisis augue orci, id dictum nisi malesuada eget. Donec at posuere sapien. Curabitur nunc augue, tempor sit amet ultrices ac, porta et sapien. Sed faucibus tincidunt sollicitudin. Praesent tempor luctus nunc, et vestibulum mi ultricies a. Quisque nibh sapien, egestas ac nibh semper, blandit ornare nulla. Pellentesque ornare commodo dolor, ut mattis lectus eleifend eu. Ut imperdiet leo magna, a accumsan neque congue a. Cras sed elementum felis, ut sagittis quam. Praesent fringilla dolor tristique ligula placerat, sed placerat orci eleifend. Praesent placerat viverra erat, non interdum sapien tincidunt nec. Aliquam viverra vehicula augue, sed pretium leo convallis sed.</p>
        </div>

    {% endblock content %}

go/core/templates/core/home.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <script>
            var comments = "";
            var json = '{{ json }}';
        </script>

        <div class="four columns">
            <div class="subhead">
                <h6>calls to play</h6>
                <a href="{% url "games:new" %}">all&nbsp;&nbsp;<i class="fa fa-long-arrow-right"></i></a>
            </div>
            <br>
            <br>
            <div id="main-callings" style="padding: 0; min-height: 30px">

                {% if callings %}

                    <table class="u-full-width">
                        <tbody>
                                {% for call in callings %}
                                    <tr onclick="window.document.location='{% url "games:show_callings" %}';">
                                        <td>{{ call.caller }}<span>({{ call.caller.rating }})</span></td>
                                        <td>{{ call.game_info.board_size }}x{{ call.game_info.board_size }}</td>
                                        <td>{{ call.game_info.main_basic_time|date:"H:i:s" }}</td>
                                    </tr>
                                {% endfor %}
                        </tbody>
                    </table>

                {% else %}

                    <span style="padding: 10px">No callings yet..</span>

                {% endif %}

            </div>
        </div>

        <div class="seven columns">
            <div class="subhead">
                <h6>games, which played now</h6>
                <a href="{% url "games:show_page" %}">all&nbsp;&nbsp;<i class="fa fa-long-arrow-right"></i></a>
            </div>
            <br>
            <div class="row">
                <div class="six columns">
                    <div id="th_1" style="margin-top: 10px"></div>
                    <div id="th_3" style="margin-top: 20px"></div>
                </div>
                <div class="six columns">
                    <div id="th_2" style="margin-top: 10px"></div>
                    <div id="th_4" style="margin-top: 20px"></div>
                </div>
            </div>
        </div>

{#                    <div id="th_4" style="margin-top: 15px"></div>#}

        <img id="bg" src="{% static "images/background1.png" %}" style="display: none;">

        <script src="{% static "js/goban/classes.js" %}"></script>
        <script src="{% static "js/goban/helpers.js" %}"></script>
        <script src="{% static "js/goban/draw.js" %}"></script>
        <script src="{% static "js/grid.js" %}"></script>
        <script>
            show(265, 265, 4, json, "th_", 13.5);
        </script>

    {% endblock content %}

go/core/templates/core/signup.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <div class="five columns with-min-height">

            <form class="full-width-form" action="{% url "home:sign_up" %}" method="post">
                {% csrf_token %}
                <p>Please, enter base account information.</p>
                <div class="fieldWrapper">
                    {{ form.username.errors }}
                    <label for="{{ form.username.id_for_label }}">Username: *</label>
                    {{ form.username }}
                </div>
                <div class="fieldWrapper">
                    {{ form.password.errors }}
                    <label for="{{ form.password.id_for_label }}">Password: *</label>
                    {{ form.password }}
                </div>
                <div class="fieldWrapper">
                    {{ form.email.errors }}
                    <label for="{{ form.email.id_for_label }}">Email: *</label>
                    {{ form.email }}
                </div>

                <hr class="divider">

                <p>Also you can enter the information about yourself, but it's not required.</p>
                <div class="fieldWrapper">
                    {{ form.first_name.errors }}
                    <label for="{{ form.first_name.id_for_label }}">First name:</label>
                    {{ form.first_name }}
                </div>
                <div class="fieldWrapper">
                    {{ form.gender.errors }}
                    <label for="{{ form.gender.id_for_label }}">Gender:</label>
                    {{ form.gender }}
                </div>

                <hr class="divider">

                <input class="button-primary" type="submit" value="Sign up">
            </form>
        </div>

    {% endblock content %}

go/core/templates/core/welcome.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}


        <div class="three columns with-min-height" style="margin-top: -0.2%">
            <form class="full-width-form" action="{% url "home:welcome_page" %}" method="post">
                {% csrf_token %}
                <span class="error">{{ wrong }}</span>
                {{ form }}
                <input class="button-primary" type="submit" value="Sign in">
                <a class="button-primary" href="{% url "home:sign_up" %}">Sign Up</a>
            </form>
        </div>
        <div class="eight columns u-full-width">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam sed commodo ante. Vestibulum sed placerat velit. Proin ornare aliquet facilisis. Proin tempor non leo ornare efficitur. Proin dictum venenatis leo, at pharetra lacus maximus non. Nulla suscipit sit amet velit a lobortis. Vivamus vel consectetur massa, ac congue nulla. Phasellus non dolor mi. Mauris enim nisi, facilisis sed arcu non, pulvinar vehicula nisl. Ut a lorem facilisis, tempor velit sit amet, maximus justo. Nullam a augue venenatis, aliquam risus ut, consectetur leo. Sed malesuada massa quam, a molestie nisl blandit et. Phasellus quis odio metus</p>
            <p>Cras mattis enim vitae lorem lacinia, eget fringilla urna venenatis. Nam ut tellus a velit mattis tincidunt. Morbi non nisl dui. Vivamus convallis lacinia diam. Vivamus cursus mi lacus, ut imperdiet magna elementum ut. Aliquam consectetur, justo eu fringilla gravida, nunc justo porttitor odio, in porttitor nulla mauris eu tellus. Fusce erat arcu, porta commodo pulvinar ac, blandit in velit.</p>
        </div>

    {% endblock content %}