go/games/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from games.views import CreatePageView

urlpatterns = [
    url(r'^new$', login_required(CreatePageView.as_view(), login_url=reverse_lazy('core:welcome')), name='new'),
    url(r'^games/(?P<game_id>\d+)?$', 'games.views.show_page', name='show_page'),
    url(r'^games/(?P<game_id>\d+)/move$', 'games.sgf.record'),
    url(r'^games/(?P<game_id>\d+)/load$', 'games.sgf.load'),
    url(r'^games/(?P<game_id>\d+)/time$', 'games.sgf.time'),
    url(r'^games/(?P<game_id>\d+)/status$', 'games.game.status'),
    url(r'^games/(?P<game_id>\d+)/surrender$', 'games.game.surrender'),
    url(r'^games/(?P<game_id>\d+)/comments$', 'games.game.comments', name='comments'),
    url(r'^callings/(?P<call_id>\d+)?$', 'games.views.show_callings', name='show_callings'),
    url(r'^callings/(?P<call_id>\d+)/accept$', 'games.views.accept', name='accept'),
    url(r'^callings/check', 'games.views.calls_check'),
    url(r'^callings/recd', 'games.views.received_accept'),
]

go/go/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from go import settings

urlpatterns = [
    # url(r'^', include('django_socketio.urls')),
    url(r'^', include('core.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ladders/', include('ladders.urls', namespace='ladders')),
    url(r'^words/', include('words.urls', namespace='words')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^', include('games.urls', namespace='games')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

go/users/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^(?P<user_id>\d+)/$', 'users.views.profile_page', name='profile_page'),
    url(r'^(?P<user_id>\d+)/games/now$', 'users.views.grid_now', name='now'),
    url(r'^(?P<user_id>\d+)/games/all$', 'users.views.grid_all', name='all'),
    url(r'^settings/$', 'users.views.settings_page', name='settings'),
]

go/users/models.py
from datetime import datetime
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('N', 'None')
)


class Profile(models.Model):
    user = models.OneToOneField(User)
    gender = models.CharField(max_length=1, default='N', choices=GENDER)
    about_me = models.TextField(blank=True)
    rating = models.PositiveIntegerField(default=0)

    def __unicode__(self):
        return self.user.username

go/users/forms.py
from django import forms
from core.models import Collection

GENDER = (
    ('M', 'Male'),
    ('F', 'Female'),
    ('N', 'None')
)

PASSWORD = {
    'required': 'This field is required',
    'invalid': 'Enter a valid value'
}


class SettingsForm(forms.Form):
    username = forms.CharField()
    first_name = forms.CharField(required=False)
    current_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    repeat_password = forms.CharField(widget=forms.PasswordInput, required=False)
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=GENDER, required=False)
    about_me = forms.CharField(widget=forms.Textarea, required=False)


class UploadForm(forms.ModelForm):
    class Meta:
        model = Collection
        exclude = ['owner']

go/users/views.py
import json
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse_lazy
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.core.exceptions import ObjectDoesNotExist


# Create your views here
from django.utils.safestring import SafeString
from core.models import Collection
from games.models import Game
from users.forms import SettingsForm, UploadForm
from users.models import Profile


@login_required(login_url=reverse_lazy("home:welcome_page"))
def profile_page(request, user_id=None):
    profile = Profile.objects.get(user=User.objects.get(id=user_id))
    if profile.user == request.user:
        own = True
    else:
        own = False
    i = 0
    now = {}
    all = {}

    now_played = Game.objects.exclude(winner__isnull=False).filter(Q(white=profile) | Q(black=profile))
    played = Game.objects.exclude(winner__isnull=True).filter(Q(white=profile) | Q(black=profile))

    for game in now_played.iterator():
        now[i] = {"game_size": game.game_info.board_size,
                  "game_id": game.game_info.id,
                  "now": True,
                  "black": game.black.user.username,
                  "black_rating": game.black.rating,
                  "white": game.white.user.username,
                  "white_rating": game.white.rating}
        i += 1

    i = 0
    for game in played.iterator():
        all[i] = {"game_size": game.game_info.board_size,
                  "game_id": game.game_info.id,
                  "now": False,
                  "black": game.black.user.username,
                  "black_rating": game.black.rating,
                  "white": game.white.user.username,
                  "white_rating": game.white.rating}
        i += 1

    # if own profile
    if request.method == 'POST':
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            game = Collection(file=request.FILES['file'],
                              comment=form.cleaned_data['comment'],
                              owner=Profile.objects.get(user=request.user))
            game.save()
            return HttpResponseRedirect(reverse_lazy('profile:profile_page', args=[request.user.id]))
        else:
            return render(request, 'users/profile.html', {'headline': profile.user.username + ' profile',
                                                          'own': own,
                                                          'user_id': user_id,
                                                          'profile': profile,
                                                          'form': form})
    elif request.method == "GET":
        form = UploadForm()
        collection = Collection.objects.filter(owner=Profile.objects.get(id=user_id))
        return render(request, "users/profile.html", {"headline": profile.user.username + " profile",
                                                      "own": own,
                                                      'user_id': user_id,
                                                      'profile': profile,
                                                      'collection': collection,
                                                      'form': form,
                                                      "now": SafeString(json.dumps(now)),
                                                      "all": SafeString(json.dumps(all))})


    # if somebody's
    else:
        try:
            return render(request, 'users/profile.html', {'headline': profile.user.username + ' profile',
                                                          'own': own,
                                                          'user_id': user_id,
                                                          'profile': profile,
                                                          "now": SafeString(json.dumps(now)),
                                                          "all": SafeString(json.dumps(all))})
        except ObjectDoesNotExist:
            return render(request, 'blank.html', {'headline': '404 profile',
                                                  'message': 'Sorry, the profile does not exist.'})


@login_required(login_url=reverse_lazy("home:welcome_page"))
def settings_page(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == 'POST':

        form = SettingsForm(request.POST)
        if form.is_valid():

            user = authenticate(
                username=request.user.username,
                password=form.cleaned_data['current_password']
            )

            if user:

                user = User.objects.get(id=request.user.id)
                profile = Profile.objects.get(user=request.user)

                user.username = form.cleaned_data['username']
                user.first_name = form.cleaned_data['first_name']

                if form.cleaned_data['password'] == form.cleaned_data['repeat_password'] \
                        and form.cleaned_data['password']:
                    user.set_password(form.cleaned_data['password'])
                    user.save()
                    reloginned = authenticate(username=profile.user.username, password=form.cleaned_data['password'])
                    login(request, reloginned)

                elif form.cleaned_data['password'] != form.cleaned_data['repeat_password'] \
                        and form.cleaned_data['password'] and form.cleaned_data['repeat_password']:
                    return render(request, 'users/settings.html', {'headline': profile.user.username + ' profile',
                                                                   'form': form,
                                                                   'not_match': 'Passwords doesn\'t match!'})

                user.email = form.cleaned_data['email']
                profile.gender = form.cleaned_data['gender']
                profile.about_me = form.cleaned_data['about_me']

                user.save()
                profile.save()
                return render(request, 'users/settings.html', {'headline': profile.user.username + ' profile',
                                                               'form': form})
            else:
                return render(request, 'users/settings.html', {'headline': profile.user.username + ' profile',
                                                               'form': form,
                                                               'wrong_pass': 'Wrong password!'})
        else:
            return render(request, 'users/settings.html', {'headline': profile.user.username + ' profile',
                                                           'form': form})

    else:
        form_data = {
            'username': request.user.username,
            'first_name': first_name_field(request.user),
            'current_password': True,
            'password': True,
            'repeat_password': True,
            'email': request.user.email,
            'gender': gender_field(request.user.profile),
            'about_me': about_me_field(request.user.profile)
        }
        form = SettingsForm(form_data)

    return render(request, 'users/settings.html', {'headline': profile.user.username + " profile",
                                                   'form': form})


@login_required(login_url=reverse_lazy("home:welcome_page"))
def grid_now(request, user_id=None):
    profile = Profile.objects.get(user=User.objects.get(id=user_id))

    now_played = Game.objects.exclude(winner__isnull=False).filter(Q(white=profile) | Q(black=profile))

    i = 0
    response = {}

    for game in now_played.iterator():
        response[i] = {"game_size": game.game_info.board_size,
                       "game_id": game.game_info.id,
                       "now": True,
                       "black": game.black.user.username,
                       "black_rating": game.black.rating,
                       "white": game.white.user.username,
                       "white_rating": game.white.rating}
        i += 1

    return render(request, "games/grid.html", {"headline": profile.user.username + " played now",
                                               "json": SafeString(json.dumps(response))})


@login_required(login_url=reverse_lazy("home:welcome_page"))
def grid_all(request, user_id=None):
    profile = Profile.objects.get(user=User.objects.get(id=user_id))

    all_played = Game.objects.exclude(winner__isnull=True).filter(Q(white=profile) | Q(black=profile))

    i = 0
    response = {}

    for game in all_played.iterator():
        response[i] = {"game_size": game.game_info.board_size,
                       "game_id": game.game_info.id,
                       "now": True,
                       "black": game.black.user.username,
                       "black_rating": game.black.rating,
                       "white": game.white.user.username,
                       "white_rating": game.white.rating}
        i += 1

    return render(request, "games/grid.html", {"headline": profile.user.username + " played",
                                               "json": SafeString(json.dumps(response))})


def first_name_field(user):
    if user.first_name:
        return user.first_name
    return ' '


def gender_field(profile):
    if profile.gender:
        return profile.gender
    return ' '


def about_me_field(profile):
    if profile.about_me:
        return profile.about_me
    return ' '

go/users/templates/users/profile.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <script>
            var now_json = '{{ now }}';
            var all_json = '{{ all }}';
            var comments = "";
        </script>

        <form action="{% url "profile:profile_page" user.id %}" id="upload-form" class="mfp-hide upload-file-popup" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Upload File</h2>
            <hr class="divider">
            <div class="fieldWrapper">
                {{ form.file.errors }}
                <label for="{{ form.file.id_for_label }}">File:</label>
                {{ form.file }}
            </div>

            <div class="fieldWrapper full-width-field">
                {{ form.comment.errors }}
                <label for="{{ form.comment.id_for_label }}">Comments:</label>
                {{ form.comment }}
            </div>

            <hr class="divider">
            <input type="submit" value="Upload">
        </form>



        <div class="three columns">
            <div class="subhead">
                <p>info</p>
                {% if own %}
                    <a href="{% url 'profile:settings' %}">settings&nbsp;&nbsp;<i class="fa fa-cog"></i></a>
                {% endif %}
            </div>
            <br>
            <br>

            <div class="stroke-block" style="min-height: 100px">

                <div>
                    <h6 class="profile-tag" style="margin-bottom: 0">Rating:</h6>
                    {{ profile.rating }}
                </div>

                {% if profile.gender != 'N' or user.first_name %}
                    <hr class="divider" style="margin-top: 10px">

                    <div class="row">
                        <div class="six columns">
                            <h6 class="profile-tag" style="margin-bottom: 0">Real name:</h6>
                            {% if user.first_name %}
                                {{ user.first_name }}
                            {% else %}
                                <span style="color: rgba(197, 62, 60, 0.37)">None</span>
                            {% endif %}
                        </div>
                        <div class="six columns">
                            <h6 class="profile-tag" style="margin-bottom: 0">Gender:</h6>
                            {% if profile.gender != 'N' %}
                                {% if profile.gender == 'M' %}
                                    {{ profile.gender }}ale
                                {% else %}
                                    {{ profile.gender }}emale
                                {% endif %}
                            {% else %}
                                <span style="color: rgba(197, 62, 60, 0.37)">None</span>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}

                {% if user.email %}
                    <hr class="divider" style="margin-top: 10px">

                    <div>
                        <h6 class="profile-tag" style="margin-bottom: 0; ">Email:</h6>
                        {{ user.email }}
                    </div>
                {% endif %}

                {% if profile.about_me %}
                    <hr class="divider" style="margin-top: 10px">

                    <div>
                        <h6 class="profile-tag" style="margin-bottom: 0; ">About me:</h6>
                        {{ profile.about_me }}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="eight columns">

            {% if now|length > 2 %}
                <div class="subhead">
                    <h6>played now</h6>
                    <a href="{% url 'profile:now' user_id %}">all&nbsp;&nbsp;<i class="fa fa-long-arrow-right"></i></a>
                </div>
                <div class="row" style="margin-top: 10px;">
                    <div id="now_1" class="four columns" style="margin-right: 14px"></div>
                    <div id="now_2" class="four columns"></div>
                    <div id="now_3" class="four columns"></div>
                </div>
                <br>
            {% endif %}


            {% if all|length > 2 %}
                <div class="subhead" style="margin-top: 20px">
                    <h6>all played games</h6>
                    <a href="{% url 'profile:all' user_id %}">all&nbsp;&nbsp;<i class="fa fa-long-arrow-right"></i></a>
                </div>

                <div class="row" style="margin-top: 10px;">
                    <div id="all_1" class="four columns" style="margin-right: 14px"></div>
                    <div id="all_2" class="four columns"></div>
                    <div id="all_3" class="four columns"></div>
                </div>
                <br>
            {% endif %}

            <div class="subhead">
                <h6>collection</h6>
                <a href="{% url 'games:show_page' %}">all&nbsp;&nbsp;<i class="fa fa-long-arrow-right"></i></a>
                {% if own %}
                    <a class="popup-with-form"  style="margin-right: 2px" href="#upload-form">new file&nbsp;&nbsp;<i class="fa fa-plus"></i></a>
                {% endif %}
            </div>
            {% if collection %}
                <table class="u-full-width">
                    <thead>
                        <tr>
                            <th>File</th>
                            <th>Upload time</th>
                            <th>Comments</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for c in collection %}
                            <tr>
                                <td>{{ c.file }}</td>
                                <td>{{ c.upload_time }}</td>
                                <td>{{ c.comment }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
{#                <div class="row" style="margin-top: 10px;">#}
{#                    <div id="coll_1" class="four columns" style="margin-right: 14px"></div>#}
{#                    <div id="coll_2" class="four columns"></div>#}
{#                    <div id="coll_3" class="four columns"></div>#}
{#                </div>#}
{#                <br>#}
            {% else %}
                <br>
                There is no any files.
            {% endif %}

            {% if now|length == 2 and all|length == 2 %}
                This player has not played any games.
            {% endif %}

        </div>

        <img id="bg" src="{% static "images/background1.png" %}" style="display: none;">

        <script src="{% static "js/goban/classes.js" %}"></script>
        <script src="{% static "js/goban/helpers.js" %}"></script>
        <script src="{% static "js/goban/draw.js" %}"></script>
        <script src="{% static "js/grid.js" %}"></script>

        <script>
            show(220, 220, 3, now_json, "now_", 10.5);
            console.log(all_json);
            show(220, 220, 3, all_json, "all_", 10.5);
        </script>


    {% endblock content %}

go/users/templates/users/settings.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <div class="five columns with-min-height" style="margin-top: -0.2%" xmlns="http://www.w3.org/1999/html">
            <form class="full-width-form" action="{% url "profile:settings" %}" method="POST">
                {% csrf_token %}
{#                <p>There is the current information about you.</p>#}
                <div class="fieldWrapper">
                    {{ form.username.errors }}
                    <label for="{{ form.username.id_for_label }}">Username:</label>
                    {{ form.username }}
                </div>
                <hr class="divider">

                <div class="fieldWrapper">
                    {{ form.first_name.errors }}
                    <label for="{{ form.first_name.id_for_label }}">Real name:</label>
                    {{ form.first_name }}
                </div>
                <hr class="divider">

                {{ not_match }}
                <div class="fieldWrapper">
                    {{ form.password.errors }}
                    <span class="error">{{ not_match }}</span>
                    <label for="{{ form.password.id_for_label }}">New password:</label>
                    {{ form.password }}
                </div>

                <div class="fieldWrapper">
                    {{ form.repeat_password.errors }}
                    <label for="{{ form.repeat_password.id_for_label }}">Repeat:</label>
                    {{ form.repeat_password }}
                </div>
                <hr class="divider">

                <div class="fieldWrapper">
                    {{ form.email.errors }}
                    <label for="{{ form.email.id_for_label }}">Email:</label>
                    {{ form.email }}
                </div>
                <hr class="divider">

                <div class="fieldWrapper">
                    {{ form.gender.errors }}
                    <label for="{{ form.gender.id_for_label }}">Gender:</label>
                    {{ form.gender }}
                </div>

                <div class="fieldWrapper">
                    {{ form.about_me.errors }}
                    <label for="{{ form.about_me.id_for_label }}">About me:</label>
                    {{ form.about_me }}
                </div>

                <hr class="divider">
                <p>To apply changes enter your current password.</p>
                <div class="fieldWrapper">
                    {{ form.current_password.errors }}
                    <span class="error">{{ wrong_pass }}</span>
                    <label for="{{ form.current_password.id_for_label }}">Current password:</label>
                    {{ form.current_password }}
                </div>
                <hr class="divider">

                <input class="button-primary u-full-width" type="submit" value="Submit">
            </form>
        </div>
        <div class="five columns u-full-width" style="margin-top: 1.75%">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc at placerat mauris. Quisque mi erat, sagittis tincidunt est a, porta molestie purus. Morbi neque nisi, porta quis ipsum sit amet, pulvinar viverra purus. Sed et lorem dolor.
            </p>
        </div>


    {% endblock content %}