go/go/urls.py
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from go import settings

urlpatterns = [
    # url(r'^', include('django_socketio.urls')),
    url(r'^', include('core.urls', namespace='home')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ladders/', include('ladders.urls', namespace='ladders')),
    url(r'^words/', include('words.urls', namespace='words')),
    url(r'^profile/', include('users.urls', namespace='profile')),
    url(r'^', include('games.urls', namespace='games')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

go/users/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^(?P<user_id>\d+)/$', 'users.views.profile_page', name='profile_page'),
    url(r'^(?P<user_id>\d+)/games/now$', 'users.views.grid_now', name='now'),
    url(r'^(?P<user_id>\d+)/games/all$', 'users.views.grid_all', name='all'),
    url(r'^settings/$', 'users.views.settings_page', name='settings'),
]

go/words/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^(?P<room_id>\d+)?$', 'words.views.show_page', name='show_page'),
    url(r'^(?P<room_id>\d+)/become$', 'words.views.get_in', name='get_in'),
]

go/words/models.py
from django.db import models

# Create your models here.
from users.models import Profile


class Room(models.Model):
    title = models.CharField(max_length=16)
    users = models.ManyToManyField(Profile)

    def __unicode__(self):
        return self.title


class Message(models.Model):
    sender = models.ForeignKey(Profile)
    room = models.ForeignKey(Room)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s | %s | %s" % (self.room, self.sender, self.text)


class Comment(models.Model):
    sender = models.ForeignKey(Profile)
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s at %s: %s" % (self.sender, self.pub_date, self.text)

go/words/forms.py
from django import forms
from words.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

go/words/views.py
import json
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here
from users.models import Profile
from words.models import Message, Room


@login_required(login_url=reverse_lazy("home:welcome_page"))
def show_page(request, room_id=None):
    response = {}
    in_room = False
    if room_id is None:
        room_id = 1
    profile = Profile.objects.get(user=request.user)
    r_room = Room.objects.get(id=room_id)

    if request.method == 'POST':
        if profile in r_room.users.all():
            word = Message(sender=profile, room=r_room, text=request.POST['text'])
            word.save()

            time = '(%s:%s, %s.%s.%s)' % (word.pub_date.hour, word.pub_date.minute, word.pub_date.day, word.pub_date.month, word.pub_date.year)
            response[0] = {'me': True, 'sender': word.sender.user.username, 'text': word.text, 'pub_date': time}
        return HttpResponse(json.dumps(response))

    elif request.is_ajax() and request.method == 'GET':
        if profile in r_room.users.all():
            i = 0
            messages = Message.objects.filter(room=r_room)
            for item in messages.iterator():
                time = '(%s:%s, %s.%s.%s)' % (
                    item.pub_date.hour, item.pub_date.minute, item.pub_date.day, item.pub_date.month, item.pub_date.year)
                c = {'me': False, 'sender': item.sender.user.username, 'text': item.text, 'pub_date': time}
                if item.sender.user == request.user:
                    c['me'] = True
                response[i] = c
                i += 1
        return HttpResponse(json.dumps(response))

    else:
        messages = None
        rooms = Room.objects.raw("SELECT * FROM words_room")
        users = r_room.users.all()
        if profile in r_room.users.all():
            in_room = True
            messages = Message.objects.filter(room=r_room)
        return render(request, "words/chat.html", {"headline": r_room.title,
                                                   "room_id": room_id,
                                                   "rooms": rooms,
                                                   "in_room": in_room,
                                                   "users": users,
                                                   "words": Message.objects.filter(room=r_room).count(),
                                                   "messages": messages})


@login_required
def get_in(request, room_id=None):
    if request.method == "POST":
        room = Room.objects.get(id=room_id)
        room.users.add(Profile.objects.get(user=request.user))
        return render(request, "words/chat.html", {"headline": room.title,
                                                   "room_id": room_id,
                                                   "rooms": Room.objects.all(),
                                                   "in_room": True,
                                                   "users": room.users.all(),
                                                   "words": Message.objects.filter(room=room).count(),
                                                   "messages": Message.objects.filter(room=room)})

go/words/templates/words/chat.html
{% extends "basic.html" %}
{% load staticfiles %}

    {% block content %}

        <script>
            var room_id = {{ room_id }};
            var words = {{ words }};
        </script>

        <div class="eight columns">
            <div id="window" class="chat-window with-scrollbar">
                {% if messages %}
                    {% for item in messages %}
                        <p>
                            {% if item.sender.user == user %}
                                <a href="{% url "profile:profile_page" item.sender.user.id %}" style="font-weight: 800; text-decoration: none">{{ item.sender }}&nbsp;{{ item.pub_date|date:"(H:s, d.m.y)" }}</a> <br>
                            {% else %}
                                <a href="{% url "profile:profile_page" item.sender.user.id %}" style="font-weight: 500; text-decoration: none">{{ item.sender }}&nbsp;{{ item.pub_date|date:"(H:s, d.m.y)" }}</a> <br>
                            {% endif %}
                            {{ item.text }}
                        </p>
                    {% endfor %}
                {% elif not in_room %}
                    <div style="margin-top: 10%" class="row">
                        <div class="five columns offset-by-two">
                            <p style="margin: 0 auto 10px 0">You are not a member in this room.</p>
                            <form action="{% url "words:get_in" room_id %}" method="POST">
                                <input id="csrf" type="hidden" name="csrfmiddlewaretoken">
                                <input class="button-primary u-full-width" type="submit" value="Become a member">
                            </form>
                        </div>
                    </div>
                {% endif %}
            </div>

            {% if in_room %}
                <div class="row">
                    <input id="id_text" type="text" class="ten columns">
                    <input id="comment-form" class="two columns" type="button" value="Send">
                </div>
            {% endif %}

        </div>

        <div class="three columns">
            <div class="stroke-block chat-block">
                <h6>Users in this room</h6>
                <div class="chat-block-list with-scrollbar">
                    {% for u in users %}
                        <a href="{% url "profile:profile_page" u.user.id %}" style="text-decoration: none; color: black;">{{ u }}</a><br>
                    {% endfor %}
                </div>
            </div>
            <div class="stroke-block chat-block" style="margin-top: 18px">
                <h6>Rooms</h6>
                <div id="rooms" class="chat-block-list with-scrollbar">
                    {% for r in rooms %}
                        <a href="{% url "words:show_page" r.id %}" style="text-decoration: none; color: black;">{{ r }}</a><br>
                    {% endfor %}
                </div>
            </div>

        </div>

        <script src="{% static "js/words-page.js" %}"></script>
        <script>
            var chat = document.getElementById("window");
            chat.scrollTop = chat.scrollHeight - chat.clientHeight;
            document.getElementById("csrf").setAttribute('value', Cookies.get("csrftoken"));
        </script>

    {% endblock content %}